export const reorderClasses = {
	treeRoot: "reorder-posts-tree-root",
	treeDragging: "reorder-posts-tree-is-dragging",
	draggingSource: "reorder-posts-tree-dragging-source",
	placeholderContainer: "reorder-posts-tree-placeholder",
	dropTarget: "reorder-posts-tree-drop-target",
	canDrop: "reorder-posts-tree-can-drop",
	node: "reorder-posts-node",
	nodeContent: "reorder-posts-node-content",
	nodeExpandWrap: "reorder-posts-node-expand-wrap",
	nodeExpand: "reorder-posts-node-expand",
	nodeExpandOpen: "is-open",
	nodeTypeIcon: "reorder-posts-node-type-icon",
	nodeLabelWrap: "reorder-posts-node-label-wrap",
	nodeLabel: "reorder-posts-node-label",
	nodeIsDropTarget: "is-drop-target",
	nodeIsDragging: "is-dragging",
	placeholder: "reorder-posts-placeholder",
	dragPreview: "reorder-posts-drag-preview",
	dragPreviewIcon: "reorder-posts-drag-preview-icon",
	dragPreviewLabel: "reorder-posts-drag-preview-label",
	loadMoreWrap: "reorder-posts-load-more",
	loadMoreButton: "reorder-posts-load-more-button",
} as const;
